// apps/angular/src/app/app.component.ts
import { Component, computed, signal } from '@angular/core';
import { NgIf, NgFor, KeyValuePipe } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { DocButtonComponent } from '../components/doc-button/doc-button.component';
import { CardWrapper } from '../components/card-wrapper/card-wrapper.component';
import { DaySchedule } from '../components/day-schedule/day-schedule.component';

import { addWeeks, format } from 'date-fns'
import { MatIcon } from '@angular/material/icon';
import {
  bookSlot,
  isAValidBookAppointment,
  type BookAppointment,
  type SlotTime
} from "@book-appointment/modules"
import { SlotTimeButtonComponent } from "../components/slot-time-button/slot-time-button.component";
import { BookSlotModal, type BookSlotForm } from "../components/book-slot-modal/book-slot-modal.component";
import { AppointmentsService } from '../services/appointments.service';
import { SlotsService } from '../services/slots.service';

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
  imports: [
    RouterOutlet,
    DocButtonComponent,
    DaySchedule,
    CardWrapper,
    NgIf,
    NgFor,
    MatIcon,
    SlotTimeButtonComponent,
    KeyValuePipe,
    BookSlotModal
  ],
})
export class AppComponent {
  currentDayShowing = new Date()
  openModal: boolean = false
  form: Partial<BookAppointment> = {}

  formattedDate = computed(() => format(this.appointment?.start ?? new Date(), "'On' EEEE dd, LLL yyyy 'at' HH:mm"))

  constructor(
    private appointmentsService: AppointmentsService,
    private slotsService: SlotsService
  ) { }
  async ngOnInit() {
    this.slotsService.getWeeklySlots(this.currentDayShowing)
    this.appointmentsService.getCurrentAppointment()
  }

  get appointment()  {
    return this.appointmentsService.data()
  }

  get weekSlots() {
    return this.slotsService.data()
  }

  async getPrevSchedule() {
    this.currentDayShowing = addWeeks(this.currentDayShowing, -1)
    this.slotsService.getWeeklySlots(this.currentDayShowing)
  }

  async getNextSchedule() {
    this.currentDayShowing = addWeeks(this.currentDayShowing, 1)
    this.slotsService.getWeeklySlots(this.currentDayShowing)
  }

  onClickSlot(slot: SlotTime) {
    this.form.start = slot.start
    this.form.end = slot.end
    this.openModal = true
  }

  async saveForm({ comments, ...patient }: BookSlotForm) {
    this.form.comments = comments
    this.form.patient = patient

    if (isAValidBookAppointment(this.form)) {
      try {
        await bookSlot(this.form)
      } finally {
        this.openModal = false
      }
    }

    this.appointmentsService.getCurrentAppointment()
  }
}

<main class="main">
  <section>
    <h2>
      Confirm your appointment with
      <strong>{{ appointment?.doctorName }}</strong>
    </h2>

    <app-card-wrapper *ngIf="appointment" class="current-appointment-card">
      <div class="current-appointment">
        <mat-icon fontIcon="calendar_month"></mat-icon>
        <p class="paragraph">{{ formattedDate() }}</p>
      </div>
    </app-card-wrapper>
  </section>

  <section class="unexpected-situation">
    <h2>
      <strong>You have an unexpected situation?</strong>
    </h2>
    <p class="paragraph">You can change the appointment for when it suits you better</p>
  </section>

  <app-card-wrapper
    *ngIf="weekSlots"
    expandFrom="500px"
  >
    <div class="calendar">
      <app-doc-button
        icon="chevron_left"
        (onClick)="getPrevSchedule()"
      />

      <app-day-schedule
        *ngFor="let item of weekSlots | keyvalue"
        class="day"
        [date]="item.key"
        [daySchedule]="item.value"
        (onClick)="onClickSlot($event)"
      ></app-day-schedule>

      <app-doc-button
        icon="chevron_right"
        (onClick)="getNextSchedule()"
      />
    </div>

    <p see-more> See more hours </p>

    <p see-less>
      See less hours
    </p>
  </app-card-wrapper>

  <app-book-slot-modal
    [open]="openModal"
    (onClose)="openModal = false"
    (onSave)="saveForm($event)"
  ></app-book-slot-modal>

</main>


<router-outlet />

// apps/vue/src/App.vue

<template>
  <section>
      <h2>
        Confirm your appointment with 
        <strong>{{ data.appointment?.doctorName }}</strong>
      </h2>

      <card-wrapper
        v-if="data.appointment"
        class="current-appointment"
      >
        <Icon class="icon" icon="radix-icons:calendar" />
        <p class="paragraph">{{ format(data.appointment.start, "'On' EEEE dd, LLL yyyy 'at' HH:mm") }}</p>
      </card-wrapper>
  </section>

  <section class="unexpected-situation">
      <h2>
        <strong>You have an unexpected situation?</strong>  
      </h2>
      <p class="paragraph">You can change the appointment for when it suits you better</p>
  </section>

  <card-wrapper
    v-if="data.weekSlots"
    class="calendar"
    expand-from="500px"
  >
    <icon-button 
      icon="material-symbols:chevron-left" 
      @click="getPrevSchedule"
    />
    
    <day-schedule 
      v-for="(info, day) in data.weekSlots"
      class="day"
      :key="day"
      :date="day"
      :day-schedule="info"
      @on-click="openModal"
    />

    <icon-button 
      icon="material-symbols:chevron-right" 
      @click="getNextSchedule"
    />

    <template #see-more>
      See more hours
    </template>

    <template #see-less>
      See less hours
    </template>
  </card-wrapper>

  <book-slot-modal 
    :open="data.openModal"
    @on-close="data.openModal = false"
    @on-save="saveForm"
  />
</template>

<script setup lang="ts">
import { reactive } from 'vue'
import { addWeeks, format } from "date-fns"
import { Icon } from '@iconify/vue'
import BookSlotModal, { type BookSlotForm } from '@/components/BookSlotModal.vue'
import type { DeepPartial } from '@/types/deepPartial'
import {
  getWeeklySlots,
  getCurrentAppointment,
  bookSlot,
  isAValidBookAppointment,
  type Appointment,
  type WeekSlots,
  type BookAppointment,
  type SlotTime
} from "@book-appointment/modules"

import IconButton from '@/components/DocButton.vue'
import DaySchedule from '@/components/DaySchedule.vue'
import CardWrapper from '@/components/CardWrapper.vue'

interface Data {
  weekSlots?: WeekSlots
  appointment?: Appointment
  today: Date
  currentDayShowing: Date
  openModal?: boolean
  form: DeepPartial<BookAppointment>
}

const data = reactive<Data>({
  today: new Date(),
  currentDayShowing: new Date(),
  form: {}
})

async function getNextSchedule() {
  data.currentDayShowing = addWeeks(data.currentDayShowing, 1)
  data.weekSlots = await getWeeklySlots(data.currentDayShowing)
}

async function getPrevSchedule() {
  data.currentDayShowing = addWeeks(data.currentDayShowing, -1)
  data.weekSlots = await getWeeklySlots(data.currentDayShowing)
}

async function created() {
  data.weekSlots = await getWeeklySlots(data.today)
  data.appointment = await getCurrentAppointment()
}

function openModal (slot: SlotTime) {
  data.form.start = slot.start
  data.form.end = slot.end
  data.openModal = true
}

async function saveForm({ comments, ...patient }: BookSlotForm) {
  data.form.comments = comments
  data.form.patient = patient
  if (isAValidBookAppointment(data.form)) {
    try {
      await bookSlot(data.form)
    } finally {
      data.openModal = false
    }
  }

  data.appointment = await getCurrentAppointment()
}

created()
</script>

<style lang="postcss" scoped>
strong {
  font-weight: 700
}

.calendar {
  display: grid;
  grid-template-columns: repeat(9, 1fr);
  padding: 32px;
  text-align: center;
  justify-items: center;
  margin: 2rem 0;
}

.current-appointment {
  display: flex;
  gap: 8px;
  align-items: center;
  margin: 2rem 0;

  & .icon {
    width: 1.5rem;
    height: 1.5rem;
  }

  & .paragraph {
    font-weight: 600;
  }
}

.unexpected-situation {
  & .paragraph {
    font-size: 1.4rem;
  }
}
</style>
