// apps/angular/src/components/book-slot-modal/book-slot-modal.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { FormGroup, FormsModule, FormBuilder, Validators, ReactiveFormsModule } from '@angular/forms';
import { DocInputComponent } from '../doc-input/doc-input.component';
import { DocButtonComponent } from "../doc-button/doc-button.component";

export interface BookSlotForm {
  name: string;
  lastName: string;
  email: string;
  phone: string;
  comments: string;
}

@Component({
  standalone: true,
  selector: 'book-slot-modal',
  templateUrl: './book-slot-modal.component.html',
  styleUrl: './book-slot-modal.component.css',
  imports: [
    FormsModule,
    ReactiveFormsModule,
    DocInputComponent,
    DocButtonComponent
]
})
export class BookSlotModal {
  @Input() open: boolean = false;
  @Output() onClose = new EventEmitter<void>();
  @Output() onSave = new EventEmitter<BookSlotForm>();

  form: FormGroup;

  constructor(private fb: FormBuilder) {
    this.form = this.fb.group({
      name: ['', Validators.required],
      lastName: ['', Validators.required],
      email: ['', Validators.required],
      phone: ['', Validators.required],
      comments: ['', Validators.required],
    });
  }

  ngOnChanges() {
    if (this.open) {
      const modal = document.querySelector('dialog');
      modal?.showModal();
    } else {
      const modal = document.querySelector('dialog');
      modal?.close();
    }
  }

  onCloseFn() {
    this.onClose.emit();
  }

  onSaveFn() {
    if (this.form.valid) {
      this.onSave.emit(this.form.value);
    }
  }
}

<dialog #modal class="dialog">
  <form [formGroup]="form" (ngSubmit)="onSaveFn()">
    <doc-input
      label="First name"
      placeholder="First name"
      formControlName="name">
    </doc-input>

    <doc-input
      label="Last name"
      placeholder="Last name"
      formControlName="lastName">
    </doc-input>

    <doc-input
      label="Email"
      placeholder="Email"
      formControlName="email">
    </doc-input>

    <doc-input
      label="Phone"
      placeholder="Phone"
      formControlName="phone">
    </doc-input>

    <doc-input
      label="Comments"
      placeholder="Comments"
      formControlName="comments">
    </doc-input>

    <div class="buttons-wrapper">
      <doc-button variant="secondary" (click)="onCloseFn()">Close</doc-button>
      <doc-button
        [disabled]="form.invalid"
        type="submit"
        data-testid="cta">
        Book
      </doc-button>
    </div>
  </form>
</dialog>

// src/components/BookSlotModal.vue
<template>
  <dialog 
    class="dialog"
    ref="modal"
  >
    <doc-input 
      label="First name"
      v-model="form.name"
    />
    <doc-input 
      label="Last name"
      v-model="form.lastName"
    />
    <doc-input 
      label="Email"
      v-model="form.email"
    />

    <doc-input 
      label="Phone"
      v-model="form.phone"
    />

    <doc-input 
      label="Comments"
      v-model="form.comments"
    />

    <div class="buttons-wrapper">
      <doc-button variant="secondary" @click="emit('on-close')">Close</doc-button>
      <doc-button
        :disabled="isDisabled"
        data-testid="cta"
        @click="emit('on-save', form)"
      >
        Book
      </doc-button>
    </div>
  </dialog>
</template>

<script setup lang="ts">
import { watchEffect, useTemplateRef, reactive, computed } from 'vue'
import DocInput from './DocInput.vue';
import DocButton from './DocButton.vue';

const modal = useTemplateRef<HTMLDialogElement>('modal')
const props = defineProps<{
  open?: boolean
}>()

const emit = defineEmits<{
  'on-close': [],
  'on-save': [BookSlotForm]
}>()

export interface BookSlotForm {
  name?: string
  lastName?: string
  email?: string
  phone?: string
  comments?: string
}

const form = reactive<BookSlotForm>({})

const isDisabled = computed(() => {
  return !(form.name && form.lastName && form.email && form.phone && form.lastName && form.comments)
})

watchEffect(() => {
  if (props.open) {
    modal.value?.showModal()
  } else {
    modal.value?.close()
  }
})


</script>

<style lang="postcss" scoped>
.dialog {
  border: none;
  border-radius: var(--radius-md);
  padding: 20px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.3);
  width: 300px;
  text-align: center;
  position: absolute;
  inset: 50%;
  transform: translate(-50%, -50%);
  z-index: 10;

  &::backdrop {
    background: rgba(0, 0, 0, 0.5);
  }
}

.buttons-wrapper {
  display: flex;
  justify-content: space-around;
  gap: 8px;
}

</style>
