// apps/angular/src/components/day-schedule/day-schedule.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { NgClass, NgFor } from '@angular/common';
import { format } from 'date-fns';
import { SlotTime } from '@book-appointment/modules'
import { SlotTimeButtonComponent } from '../slot-time-button/slot-time-button.component';

@Component({
  standalone: true,
  selector: 'day-schedule',
  templateUrl: './day-schedule.component.html',
  styleUrl: './day-schedule.component.css',
  imports: [
    SlotTimeButtonComponent,
    NgClass,
    NgFor
  ]
})
export class DaySchedule {
  @Input() date!: string;
  @Input() daySchedule!: SlotTime[];

  @Output() onClick = new EventEmitter<SlotTime>();

  formatDate(date: string, formatStr: string): string {
    return format(new Date(date), formatStr);
  }

  handleClick(slotTime: SlotTime) {
    this.onClick.emit(slotTime);
  }

  generateKey(date: string, index: number): string {
    return `${date}-${index}`;
  }
}

<div class="day">
  <p>{{ formatDate(date, 'EE') }}</p>
  <p>{{ formatDate(date, 'dd MMM') }}</p>

  <slot-time-button
    *ngFor="let slot of daySchedule; let index = index"
    class="slot-time"
    [slotTime]="slot"
    (onClick)="handleClick(slot)"
    [attr.data-key]="generateKey(date, index)"
  ></slot-time-button>
</div>

// src/components/DaySchedule.vue
<template>
  <div 
    class="day"
  >
    <p>{{ format(props.date, 'EE') }}</p>
    <p>{{ format(props.date, 'dd MMM') }}</p>

    <slot-time-button
      v-for="(slot, index) in daySchedule"
      :key="`${props.date}-${index}`"
      class="slot-time"
      :slot-time="slot"
      @on-click="emit('on-click', $event)"
    />
  </div>
</template>

<script setup lang="ts">
import { format } from "date-fns"
import SlotTimeButton from '@/components/SlotTimeButton.vue'
import type { SlotTime } from "@/modules/appointment"

const props = defineProps<{
  date: string,
  daySchedule: SlotTime[]
}>()

const emit = defineEmits<{
  'on-click': [SlotTime]
}>()

</script>

<style lang="postcss" scoped>
.day {
  display: grid;
  grid-auto-flow: row;
  grid-auto-rows: max-content;
  gap: 16px;
  width: 100%;
}
</style>
